### PR TITLE
migrate to Quarto

### PR DESCRIPTION
**Pull request by bbest**
Hi @MathewBiddle,

Continuing with #266, I was able to migrate to Quarto and have the Github Action render in [3m 39s](https://github.com/bbest/bio_data_guide/actions/runs/10730210097/job/29758264488#step:8:709), but not seeing it published per the log, presumably because I don't have write permissions to the repo **ioos/bio_data_guide**:

```
origin	https://github.com/bbest/bio_data_guide (push)
To https://github.com/bbest/bio_data_guide
   031444b..5b371e1  HEAD -> gh-pages

NOTE: GitHub Pages sites use caching so you might need to click the refresh
button within your web browser to see changes after deployment.


[✓] Published to https://ioos.github.io/bio_data_guide/

NOTE: GitHub Pages deployments normally take a few minutes (your site updates
will be visible once the deploy completes)
```

### CODE REVIEW

**Comment by MathewBiddle** [comment]
Hey @bbest! Thanks for digging into this. What I can do is merge this in on my fork, we can take a look at the rendered page and see what we have, If everything looks good, we'll push upstream.

**Review by MathewBiddle — APPROVED** [review]
Let's see what we get. I'm not up to speed on qarto, so I'm trusting your expertise. :)

**Comment by MathewBiddle** [comment]
It looks like we have some conflicts. I sync'd the `main` branch here with the upstream IOOS one. That seems to have introduced these conflicts.

**Comment by bbest** [comment]
I put a few finishing touches on the latest.

These conflicts could be resolved by simply removing the OLD files since they got moved:

- OLD: `.github/workflows/deploy_bookdown.yml`\
   NEW: `.github/workflows/deploy_book.yml`
   
- OLD: `bio-data-guide/04-tools.Rmd`\
   NEW: `tools.qmd`
   
- OLD: `datasets/atn_satellite_telemetry/atn_satellite_telemetry_netCDF2DwC.Rmd`\
   NEW: `datasets/atn_satellite_telemetry/atn_satellite_telemetry_netCDF2DwC.qmd`

**Comment by MathewBiddle** [comment]
Okay. Looks like we are all green now. LMK when you're ready to merge.

**Comment by bbest** [comment]
Go for it :) 🚀

**Comment by MathewBiddle** [comment]
Here we go: https://github.com/MathewBiddle/bio_data_guide/actions/runs/10739834872

**Comment by MathewBiddle** [comment]
And here we go! https://mathewbiddle.github.io/bio_data_guide/

Take a look.

**Comment by bbest** [comment]
Yay, looking good! ✨ 

image

Here's a few high level differences worth pointing out:

1. All the old Rmarkdown (*.Rmd) files got moved from subfolder [`bio-data-guide/##_*.Rmd`](https://github.com/MathewBiddle/bio_data_guide/tree/e60494c4acd8abfb9e0f300c85eb57c3f3b20c04/bio-data-guide) with number prefixes to **[`/*.qmd`](https://github.com/MathewBiddle/bio_data_guide)**

1. Now you describe the **sequence** of documents to render under the `chapters:` section of the **`_quarto.yml`**, including any sectional `part:` you want to add (only 1 extra level of depth allowed):\
  https://github.com/MathewBiddle/bio_data_guide/blob/b1fcc95695ab00ac95daf58935e93905b5c592f6/_quarto.yml#L25-L40
  
1. The **R package dependencies** for the Github Action are now handled simply with\
https://github.com/MathewBiddle/bio_data_guide/blob/b1fcc95695ab00ac95daf58935e93905b5c592f6/.github/workflows/render_book.yml#L42-L45
    - This installs the necessary packages from CRAN and Github based on the **`DESCRIPTION`** file:
     https://github.com/MathewBiddle/bio_data_guide/blob/b1fcc95695ab00ac95daf58935e93905b5c592f6/DESCRIPTION#L13-L37
    - Users building the Quarto book can also install these R package dependencies **locally** from the `DESCRIPTION` file per instructions here:
    https://github.com/MathewBiddle/bio_data_guide/blob/b1fcc95695ab00ac95daf58935e93905b5c592f6/refs/building-the-guide.md?plain=1#L26-L28
    - All R package dependencies are described now in the file which is best modified with **`usethis`** commands described in\
    https://github.com/MathewBiddle/bio_data_guide/blob/b1fcc95695ab00ac95daf58935e93905b5c592f6/refs/building-the-guide.md?plain=1#L82-L99
 1. This **`pre-render.R`** script downloads those pesky URL images as SVGs\
 https://github.com/MathewBiddle/bio_data_guide/blob/b1fcc95695ab00ac95daf58935e93905b5c592f6/lib/pre-render.R#L1-L22
     -  This script is baked into Quarto render process with this **`pre-render:`** hook in the `_quarto.yml`:\
         https://github.com/MathewBiddle/bio_data_guide/blob/b1fcc95695ab00ac95daf58935e93905b5c592f6/_quarto.yml#L3
     -  The SVGs get rendered into PNGs for embedding in static outputs (e.g., pdf/docx/epub) using **`librsvg`** in the GH Action [`render_book.yml`](https://github.com/MathewBiddle/bio_data_guide/blob/b1fcc95695ab00ac95daf58935e93905b5c592f6/.github/workflows/render_book.yml#L33C5-L35C20).

**Comment by MathewBiddle** [comment]
@bbest is there an automated way to build a DESCRIPTION file? Like what you created at https://github.com/ioos/bio_data_guide/blob/main/DESCRIPTION

I was trying to build one for this and ended up doing it manually, so I'm looking for tips/tricks if you have any.

**Comment by bbest** [comment]
Yes, easy, `usethis` is your friend 😉 :

[`usethis::use_description()`](https://usethis.r-lib.org/reference/use_description.html)

**Pull request merged**
